apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  labels:
    app: db
type: Opaque
data:
  POSTGRES_DB: ZGItZGF0YQ==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  PGDATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3BnZGF0YQ==